Refactored: add config files, improve code, fix error

diff --git a/bin/backup_data b/bin/backup_data
--- a/bin/backup_data
+++ b/bin/backup_data
@@ -1,50 +1,49 @@
 #!/bin/bash
-# Create individual SQL files for each database. These files
-# are imported automatically during an initial provision if
-# the databases exist per the import-sql.sh process.
 
 echo
-echo "--- Start $0"
+echo "--- Start $0 $*"
+
+exit_if_error() {
+  MESS=${2:-}
+  [ $1 != "0" ] && echo "Error!!! Code=$1";echo "$MESS"; exit 1
+  exit 0
+}
 
 set -o nounset
 set -e 
 
 TYPE="data"
 
-CNT_PARAMS=6
-if [[ $# -lt $CNT_PARAMS ]] ; then 
-  echo "Error!!! Must be $CNT_PARAMS parameters"
-  exit 1
-fi
+CNT_PARAMS=4
+[[ $# -lt $CNT_PARAMS ]] && exit_if_error $? "Must be $CNT_PARAMS parameters"
 
 ### Input parameters ###
-PERIOD=$1
-YEAR=$2
-MONTH=$3
-DAY=$4
-WEEK=$5
-DIR_ROOT=$6
+YEAR=$1
+MONTH=$2
+DAY=$3
+WEEK=$4
 
-NOW="${YEAR}${MONTH}"
-
-### Directories ###
-DIR_BIN="${DIR_ROOT}/bin"
-DIR_CFG="${DIR_ROOT}/cfg"
-DIR_ARC="${DIR_ROOT}/arc"
-DIR_LOG="${DIR_ROOT}/log"
+### Setup your default directories.
+DIR_ROOT=$(dirname "$0")
+DIR_ROOT=$("$DIR_ROOT"/get_root_dir "$0") || exit_if_error $? "Check getting root dirs for $0"
+DIR_BIN="$DIR_ROOT"/bin
+DIR_CFG="$DIR_ROOT"/cfg
+DIR_ARC="$DIR_ROOT"/arc
+DIR_LOG="$DIR_ROOT"/log
 DIR_SNAP="${DIR_ROOT}/snapshots"
+READER="$DIR_BIN/read_value_from_file"
+
+echo "Loaded list directories from ${DIR_CFG}/dirs/dirs.cfg"
 
 ### GPG settings ###
-GPG_USERID=$(cat $DIR_CFG/gpg_userid.txt)
+GPG_USERID=$($READER "$DIR_CFG/arcs/gpg_userid.cfg") || exit_if_error $? "Check $DIR_CFG/arcs/gpg_userid.cfg"
 GPG_OPT="-e -r"
-
 ### Split settings ###
-SPLIT_OPT="-d -a 3 -b $(cat $DIR_CFG/split_size.txt)"
-
+SPLIT_SIZE=$($READER "$DIR_CFG/arcs/split_size.cfg") || exit_if_error $? "Check $DIR_CFG/arcs/split_size.cfg"
+SPLIT_OPT='-d -a 3 -b '"$SPLIT_SIZE"
 ### System Setup ###
 GZIP_OPT=-c9
-DIRS=$(cat "${DIR_CFG}/dirs_${PERIOD}.lst")
-echo "Loaded list directories from ${DIR_CFG}/dirs_${PERIOD}.lst"
+DIRS=$($READER "$DIR_CFG/dirs/dirs.cfg") || exit_if_error $? "Check $DIR_CFG/dirs/dirs.cfg"
 
 #---------------------------------------------------
 [ ! -d $DIR_ARC ] && mkdir -p $DIR_ARC || :
@@ -54,14 +53,13 @@ do
   if [ -d "$DIR" ] ;
   then 
     echo 
-    echo "Backing: $DIR"
+    echo "Backup: $DIR"
 
     DATA_NAME=$(basename "$DIR")
 
     FNAME_SNAPSHOT="${DIR_SNAP}/${DATA_NAME}.snapshot"
     FNAME_SNAPSHOT_FULL="$FNAME_SNAPSHOT.full"
 
-#    if [[ "${DAY}" = '01' || "${WEEK}" -eq 0 ]] ; then
     if [[ "${DAY}" = '01' || "${DAY}" = '10' || "${DAY}" = '20' ]] ; then
       rm -f "$FNAME_SNAPSHOT_FULL"
     fi
@@ -85,7 +83,7 @@ do
       | split $SPLIT_OPT - "${BACKUP_FILE}."
     cd -
 
-    $DIR_BIN/move_file_to_remote $PERIOD $NOW $DAY $TYPE $BACKUP_FILE $DIR_ROOT
+    $DIR_BIN/move_file_to_remote $YEAR $MONTH $DAY $WEEK $TYPE $BACKUP_FILE 
     echo
     echo "Dir $DIR backed up..."
 
diff --git a/bin/backup_db b/bin/backup_db
--- a/bin/backup_db
+++ b/bin/backup_db
@@ -1,51 +1,53 @@
 #!/bin/bash
-# Create individual SQL files for each database. These files
-# are imported automatically during an initial provision if
-# the databases exist per the import-sql.sh process.
+# Create individual SQL files for each database.
 
 echo
 echo "--- Start $0 $*"
+
+exit_if_error() {
+  MESS=${2:-}
+  [[ $1 != "0" ]] && echo "Error!!! Code=$1";echo "$MESS"; exit 1
+  exit 0
+}
 
 set -o nounset
 set -e 
 
 TYPE="db"
 
-CNT_PARAMS=6
-if [[ $# -lt $CNT_PARAMS ]] ; then 
-  echo "Error!!! Must be $CNT_PARAMS parameters"
-  exit 1
-fi
+CNT_PARAMS=4
+[[ $# -lt $CNT_PARAMS ]] && exit_if_error $? "Must be $CNT_PARAMS parameters"
 
 ### Input parameters ###
-PERIOD=$1
-YEAR=$2
-MONTH=$3
-DAY=$4
-WEEK=$5
-DIR_ROOT=$6
+YEAR=$1
+MONTH=$2
+DAY=$3
+WEEK=$4
 
-NOW="${YEAR}${MONTH}"
-
-### Directories ###
-DIR_BIN="${DIR_ROOT}/bin"
-DIR_CFG="${DIR_ROOT}/cfg"
-DIR_ARC="${DIR_ROOT}/arc"
-DIR_LOG="${DIR_ROOT}/log"
+### Setup your default directories.
+DIR_ROOT=$(dirname "$0")
+DIR_ROOT=$("$DIR_ROOT"/get_root_dir "$0") || exit_if_error $? "Check getting root dirs for $0"
+DIR_BIN="$DIR_ROOT"/bin
+DIR_CFG="$DIR_ROOT"/cfg
+DIR_ARC="$DIR_ROOT"/arc
+DIR_LOG="$DIR_ROOT"/log
+DIR_SNAP="${DIR_ROOT}/snapshots"
+READER="$DIR_BIN/read_value_from_file"
 
 ### MySQL Setup ###
 DB_HOST=localhost
 DB_USER=root
 DB_PASS=Q_H9N_wzL76tCE
-DB_EXCLUDE="${DIR_CFG}/db_excludes.lst"
+DB_EXCLUDE="${DIR_CFG}/dbs/db_excludes.cfg"
+[ ! -f "$DB_EXCLUDE" ] && DB_EXCLUDE="$DB_EXCLUDE.default"
+[ ! -f "$DB_EXCLUDE" ] && exit_if_error $? "Check $DB_EXCLUDE"
 
 ### GPG settings ###
-GPG_USERID=$(cat $DIR_CFG/gpg_userid.txt)
+GPG_USERID=$($READER "$DIR_CFG/arcs/gpg_userid.cfg") || exit_if_error $? "Check $DIR_CFG/arcs/gpg_userid.cfg"
 GPG_OPT="-e -r"
-
 ### Split settings ###
-SPLIT_OPT="-d -a 3 -b $(cat $DIR_CFG/split_size.txt)"
-
+SPLIT_SIZE=$($READER "$DIR_CFG/arcs/split_size.cfg") || exit_if_error $? "Check $DIR_CFG/arcs/split_size.cfg"
+SPLIT_OPT='-d -a 3 -b '"$SPLIT_SIZE"
 ### System Setup ###
 MYSQLDUMP_OPT='--compress'
 GREP_OPT="-v -f $DB_EXCLUDE -x"
@@ -54,12 +56,10 @@ GZIP_OPT=-c9
 #---------------------------------------------------
 [ ! -d $DIR_ARC ] && mkdir -p $DIR_ARC || :
 
-echo $(dirname $0)
-echo --- See exists DBs ---
+echo "Exists DBs:"
 DB_AUTH="-h ${DB_HOST} -u ${DB_USER} -p${DB_PASS}"
 echo "mysql -e 'show databases'"
 
-echo --- Dump ---
 mysql -e 'show databases' $DB_AUTH | sort | grep $GREP_OPT | \
 while read DB_NAME; 
 do
@@ -74,8 +74,10 @@ do
     | split $SPLIT_OPT - "${BACKUP_FILE}."
   cd -
 
-  $DIR_BIN/move_file_to_remote $PERIOD $NOW $DAY $TYPE $BACKUP_FILE $DIR_ROOT
-  echo
-  echo "Database $DB_NAME backed up..."
+  $DIR_BIN/move_file_to_remote $YEAR $MONTH $DAY $WEEK $TYPE $BACKUP_FILE 
 
+  echo
+  echo "Database $DB_NAME dumped up..."
 done
+
+exit 0
diff --git a/bin/clear_remote b/bin/clear_remote
--- a/bin/clear_remote
+++ b/bin/clear_remote
@@ -1,39 +1,48 @@
 #!/bin/bash
-# Create individual SQL files for each database. These files
-# are imported automatically during an initial provision if
-# the databases exist per the import-sql.sh process.
 
-echo "--- Start $0"
+echo
+echo "--- Start $0 $*"
+
+exit_if_error() {
+  MESS=${2:-}
+  [[ $1 != "0" ]] && echo "Error!!! Code=$1";echo "$MESS"; exit 1
+  exit 0
+}
 
 set -o nounset
 set -e 
 
-print_help() {
-  echo "Usage: $0 NAME_OF_PERIOD [yymmdd]"
-}
+#CNT_PARAMS=2
+#[[ $# -lt $CNT_PARAMS ]] && exit_if_error $? "Must be $CNT_PARAMS parameters"
 
-if [[ $# -eq 0 ]]; then
-  print_help
-  exit 1
-fi
+### Input parameters ###
+YEAR=${1:-}
+MONTH=${2:-}
+DAY=${3:-}
+WEEK=${4:-}
+NOW="${YEAR}${MONTH}"
 
-PERIOD=$1
-NOW=${2:-""}
-DAY=${3:-''}
+### Setup your default directories.
+DIR_ROOT=$(dirname "$0")
+DIR_ROOT=$("$DIR_ROOT"/get_root_dir "$0") || exit_if_error $? "Check getting root dirs for $0"
+DIR_BIN="$DIR_ROOT"/bin
+DIR_CFG="$DIR_ROOT"/cfg
+DIR_ARC="$DIR_ROOT"/arc
+DIR_LOG="$DIR_ROOT"/log
+READER="$DIR_BIN/read_value_from_file"
 
-### FTP server Setup ###
-FTPD='/GREY_1TB/ToolkitVault-server-backups'
-FTPS='office.giantleaplab.com'
-FTPU='tv-backuper'
-FTPP='xn->52s4_dAHND#4'
-FTP_OPT='-c -E'
+### FTP Setup ###
 FTP="$(which lftp)"
+FTPS=$("$READER" "$DIR_CFG/ftp/server_name.cfg") || exit_if_error $? "Check $DIR_CFG/ftp/server_name.cfg"
+FTPU=$("$READER" "$DIR_CFG/ftp/user_login.cfg" ) || exit_if_error $? "Check $DIR_CFG/ftp/user_login.cfg"
+FTPP=$("$READER" "$DIR_CFG/ftp/user_pass.cfg"  ) || exit_if_error $? "Check $DIR_CFG/ftp/user_pass.cfg"
+FTPD=$("$READER" "$DIR_CFG/ftp/root_dir.cfg"   ) || exit_if_error $? "Check $DIR_CFG/ftp/root_dir.cfg"
 
-REMOVE_DIR="$FTPD/$PERIOD"
+REMOVE_DIR="$FTPD"
 if [[ ! -z $NOW ]]; then
-  REMOVE_DIR="${REMOVE_DIR}/${NOW}"
+  REMOVE_DIR="$REMOVE_DIR/$NOW"
   if [[ ! -z $DAY ]]; then
-    REMOVE_DIR="${REMOVE_DIR}/${DAY}"
+    REMOVE_DIR="$REMOVE_DIR/$DAY"
   fi
 fi 
 
@@ -41,9 +50,10 @@ fi
 echo "$FTP -u $FTPU,**** $FTPS"
 echo "rm -rf $REMOVE_DIR"
 
-$FTP -u $FTPU,$FTPP $FTPS<<EOF
+$($FTP -u $FTPU,$FTPP $FTPS<<EOF
 rm -rf "$REMOVE_DIR"
 quit
 EOF
+) || exit_if_error $? "Can not remove $REMOVE_DIR"
 
 exit 0
diff --git a/bin/move_file_to_remote b/bin/move_file_to_remote
--- a/bin/move_file_to_remote
+++ b/bin/move_file_to_remote
@@ -1,46 +1,49 @@
 #!/bin/bash
-# Create individual SQL files for each database. These files
-# are imported automatically during an initial provision if
-# the databases exist per the import-sql.sh process.
-
 
 echo
 echo "--- Start $0 $*"
+
+exit_if_error() {
+  MESS=${2:-}
+  [ $1 != "0" ] && echo "Error!!! Code=$1";echo "$MESS"; exit 1
+  exit 0
+}
 
 set -o nounset
 set -e 
 
 CNT_PARAMS=6
-if [[ $# -lt $CNT_PARAMS ]] ; then 
-  echo "Error!!! Must be $CNT_PARAMS parameters"
-  exit 1
-fi
+[[ $# -lt $CNT_PARAMS ]] && exit_if_error $? "Must be $CNT_PARAMS parameters"
 
 ### Input parameters ###
-PERIOD=$1
-NOW=$2
+YEAR=$1
+MONTH=$2
 DAY=$3
-TYPE=$4
-FNAME=$5
-DIR_ROOT=$6
+WEEK=$4
+TYPE=$5
+FNAME=$6
+NOW="${YEAR}${MONTH}"
 
-### FTP server Setup ###
-FTPD='/GREY_1TB/ToolkitVault-server-backups'
-FTPS='office.giantleaplab.com'
-FTPU='tv-backuper'
-FTPP='xn->52s4_dAHND#4'
+### Setup your default directories.
+DIR_ROOT=$(dirname "$0")
+DIR_ROOT=$("$DIR_ROOT"/get_root_dir "$0") || exit_if_error $? "Check getting root dirs for $0"
+DIR_BIN="$DIR_ROOT"/bin
+DIR_CFG="$DIR_ROOT"/cfg
+DIR_ARC="$DIR_ROOT"/arc
+DIR_LOG="$DIR_ROOT"/log
+READER="$DIR_BIN/read_value_from_file"
+
+### FTP Setup ###
 FTP="$(which lftp)"
+FTPS=$("$READER" "$DIR_CFG/ftp/server_name.cfg") || exit_if_error $? "Check $DIR_CFG/ftp/server_name.cfg"
+FTPU=$("$READER" "$DIR_CFG/ftp/user_login.cfg" ) || exit_if_error $? "Check $DIR_CFG/ftp/user_login.cfg"
+FTPP=$("$READER" "$DIR_CFG/ftp/user_pass.cfg"  ) || exit_if_error $? "Check $DIR_CFG/ftp/user_pass.cfg"
+FTPD=$("$READER" "$DIR_CFG/ftp/root_dir.cfg"   ) || exit_if_error $? "Check $DIR_CFG/ftp/root_dir.cfg"
 
-### Directories ###
-DIR_BIN="${DIR_ROOT}/bin"
-DIR_CFG="${DIR_ROOT}/cfg"
-DIR_ARC="${DIR_ROOT}/arc"
-DIR_LOG="${DIR_ROOT}/log"
+FULLPATH="${FTPD}/${NOW}/${DAY}/${TYPE}"
+echo "Copy to remote ftp server: $FULLPATH/$FNAME.*"
 
-FULLPATH="${FTPD}/${PERIOD}/${NOW}/${DAY}/${TYPE}"
-echo "Copy to remote $FULLPATH/$FNAME.*"
-
-#Start FTP backup using ncftp
+#Start FTP backup using ncftp9R
 $FTP -u $FTPU,$FTPP $FTPS<<EOF
 mkdir -p "${FULLPATH}"
 cd "${FULLPATH}"
@@ -48,3 +51,5 @@ lcd "$DIR_ARC"
 mput -E -c "$FNAME.*"
 quit
 EOF
+
+exit 0
diff --git a/bin/prepare_remote b/bin/prepare_remote
--- a/bin/prepare_remote
+++ b/bin/prepare_remote
@@ -1,41 +1,45 @@
 #!/bin/bash
-# Create individual SQL files for each database. These files
-# are imported automatically during an initial provision if
-# the databases exist per the import-sql.sh process.
+# Create individual SQL files for each database.
 
 echo
 echo "--- Start $0 $*"
 
+exit_if_error() {
+  MESS=${2:-}
+  [[ $1 != "0" ]] && echo "Error!!! Code=$1";echo "$MESS"; exit 1
+  exit 0
+}
+
 set -o nounset
 set -e 
 
-if [[ $# -ne 2 ]]; then
-  echo "Usage: $0 NAME_OF_PERIOD CNT_KEEP"
-  exit 1
-fi
+### Setup your default directories.
+DIR_ROOT=$(dirname "$0")
+DIR_ROOT=$("$DIR_ROOT"/get_root_dir "$0") || exit_if_error $? "Check getting root dirs for $0"
+DIR_BIN="$DIR_ROOT"/bin
+DIR_CFG="$DIR_ROOT"/cfg
+DIR_ARC="$DIR_ROOT"/arc
+DIR_LOG="$DIR_ROOT"/log
+READER="$DIR_BIN/read_value_from_file"
 
-PERIOD=$1
-CNT_KEEP=$2
-
-### FTP server Setup ###
-FTPD='/GREY_1TB/ToolkitVault-server-backups'
-FTPS='office.giantleaplab.com'
-FTPU='tv-backuper'
-FTPP='xn->52s4_dAHND#4'
-FTP_OPT='-c -E'
+### FTP Setup ###
 FTP="$(which lftp)"
+FTPS=$("$READER" "$DIR_CFG/ftp/server_name.cfg") || exit_if_error $? "Check $DIR_CFG/ftp/server_name.cfg"
+FTPU=$("$READER" "$DIR_CFG/ftp/user_login.cfg" ) || exit_if_error $? "Check $DIR_CFG/ftp/user_login.cfg"
+FTPP=$("$READER" "$DIR_CFG/ftp/user_pass.cfg"  ) || exit_if_error $? "Check $DIR_CFG/ftp/user_pass.cfg"
+FTPD=$("$READER" "$DIR_CFG/ftp/root_dir.cfg"   ) || exit_if_error $? "Check $DIR_CFG/ftp/root_dir.cfg"
 
-CHECK_DIR="$FTPD/$PERIOD"
-#CHECK_DIR="$FTPD/daily/150102/DB"
+echo "Prepare dir $FTPD"
 
 #Start FTP backup using ncftp
 declare -a DIRS=$($FTP -u "$FTPU,$FTPP" $FTPS<<EOF
-mkdir -p "$CHECK_DIR"
-recls -1 --sort=name $CHECK_DIR
+mkdir -p "$FTPD"
+recls -1 --sort=name $FTPD
 quit
 EOF
 )
 
+CNT_KEEP=$("$DIR_BIN/cnt_keep")
 #found keeping dir
 if [[ ! -z "$DIRS" ]]; then echo 'Found dirs:'; fi
 IND=$((-$CNT_KEEP))
@@ -53,10 +57,11 @@ do
   if [[ $CNT -gt $IND ]]; then 
     break;
   fi
-  echo "Try clear $CNT: $DIR"
+  echo "Try remove $CNT: $DIR"
   $FTP -u $FTPU,$FTPP $FTPS<<EOF
   rm -rf "$DIR"
   quit
 EOF
-
 done 
+
+exit 0
diff --git a/clear_backup b/clear_backup
--- a/clear_backup
+++ b/clear_backup
@@ -1,59 +1,68 @@
 #!/bin/bash
 
-#set -o nounset
+set -o nounset
 set -e 
 
+echo
 echo "--- Start $0 $*"
+
+exit_if_error() {
+  MESS=${2:-}
+  [[ $1 != "0" ]] && echo "Error!!! Code=$1";echo "$MESS"; exit 1
+  exit 0
+}
 
 YEAR=$(date +"%y")
 MONTH=$(date +"%m")
 DAY=$(date +"%d")
-WEEK=$(date +"%w")
+#WEEK=$(date +"%w")
+WEEK=
 
-MODE_CLEAR="help"
-if [[ $# -gt 0 ]]; then
-  MODE_CLEAR="$1"
-  if [[ $MODE_CLEAR = 'force' ]] ; then
-    if [[ ! -z $2 && $2 =~ [0-9]{2} ]]; then
-      YEAR=$2
-      if [[ ! -z $3 && $3 =~ [0-9]{2} ]]; then
-        MONTH=$3
-        if [[ ! -z $4 && $4 =~ [0-9]{2} ]]; then
-          DAY=$4
-        else 
-          DAY=''
-        fi
-      fi
-    fi
-  fi
+MODE_CLEAR=${1:-help}
+P_YEAR=${2:-}
+P_MONTH=${3:-}
+P_DAY=${4:-}
+
+[[ $# -lt 1 ]] && exit_if_error $? "Usage: $0 { full | current | force yy | force yy mm | force yy mm dd}"
+
+if [[ $MODE_CLEAR = 'force' ]] ; then
+  [[ ! -z $P_YEAR  && $P_YEAR  =~ [0-9]{2} ]] && YEAR=$P_YEAR    || YEAR=''
+  [[ ! -z $P_MONTH && $P_MONTH =~ [0-9]{2} ]] && MONTH=$P_MONTH  || MONTH=''
+  [[ ! -z $P_DAY   && $P_DAY   =~ [0-9]{2} ]] && DAY=$P_DAY      || DAY=''
+  [[ -z $MONTH ]] &&    DAY=''
+#  [[ ! -z $YEAR && -z $MONTH ]] && MONTH=''
 fi
 
-NOW="${YEAR}${MONTH}"
+### Setup your default directories.
+DIR_ROOT=$(dirname "$0")
+DIR_ROOT=$("$DIR_ROOT"/bin/get_root_dir "$0") || exit_if_error $? "Check getting root dirs for $0"
+DIR_BIN="$DIR_ROOT"/bin
+DIR_CFG="$DIR_ROOT"/cfg
+DIR_ARC="$DIR_ROOT"/arc
+DIR_LOG="$DIR_ROOT"/log
 
-
-DIR_BIN='./bin'
-PERIOD=$("$DIR_BIN"/get_period_now $YEAR $MONTH $DAY $WEEK )
-
-echo "$MODE_CLEAR YEAR=$YEAR MONTH=$MONTH DAY=$DAY WEEK=$WEEK PERIOD=$PERIOD NOW=$NOW"
+echo "$MODE_CLEAR YEAR=$YEAR MONTH=$MONTH DAY=$DAY WEEK=$WEEK"
 
 case $MODE_CLEAR in 
         "full")
-                echo $DIR_BIN/clear_remote $PERIOD
-                     $DIR_BIN/clear_remote $PERIOD
+                echo $DIR_BIN/clear_remote 
+                     $DIR_BIN/clear_remote 
                 ;;
-     "current") 
-                echo $DIR_BIN/clear_remote $PERIOD $NOW $DAY
-                     $DIR_BIN/clear_remote $PERIOD $NOW $DAY 
+     "current")
+                [[ -z $YEAR || -z $MONTH ]] && exit_if_error 1 "Check year and month" 
+                echo $DIR_BIN/clear_remote $YEAR $MONTH $DAY $WEEK
+                     $DIR_BIN/clear_remote $YEAR $MONTH $DAY $WEEK
                 ;;
        "force") 
-                echo $DIR_BIN/clear_remote $PERIOD $NOW $DAY
-                     $DIR_BIN/clear_remote $PERIOD $NOW $DAY
+                [[ -z $YEAR || -z $MONTH ]] && exit_if_error 1 "Check year and month" 
+                echo $DIR_BIN/clear_remote $YEAR $MONTH $DAY $WEEK
+                     $DIR_BIN/clear_remote $YEAR $MONTH $DAY $WEEK
                 ;;
              *) 
-                echo "Usage: $0 { full | current | force yy | force yy mm | force yy mm dd}"  
-                exit 1
+                exit_if_error 1 'Uknown mode clear'
                 ;;
 esac
+echo $?
 
 exit 0
 
diff --git a/full_backup b/full_backup
--- a/full_backup
+++ b/full_backup
@@ -3,41 +3,43 @@
 set -o nounset
 set -e 
 
-echo "--- Start $0"
+echo
+echo "--- Start $0 $*"
+
+exit_if_error() {
+  MESS=${2:-}
+  [[ $1 != "0" ]] && echo "Error!!! Code=$1";echo "$MESS"; exit 1
+  exit 0
+}
 
 ### Input parameters ###
 YEAR=$1
 MONTH=$2
 DAY=$3
 WEEK=$4
-DIR_ROOT=$5
 
-### Directories ###
-cd $DIR_ROOT
-echo "DIR_ROOT: '${DIR_ROOT}' Current dir: '$(pwd)'"
+### Setup your default directories.
+DIR_ROOT=$(dirname "$0")
+DIR_ROOT=$("$DIR_ROOT"/bin/get_root_dir "$0") || exit_if_error $? "Check getting root dirs for $0"
+DIR_BIN="$DIR_ROOT"/bin
+DIR_CFG="$DIR_ROOT"/cfg
+DIR_ARC="$DIR_ROOT"/arc
+DIR_LOG="$DIR_ROOT"/log
 
-DIR_BIN="${DIR_ROOT}"/bin
-DIR_CFG="${DIR_ROOT}"/cfg
-DIR_ARC="${DIR_ROOT}"/arc
-DIR_LOG="${DIR_ROOT}"/log
+### Prepare date
+echo "YEAR=$YEAR MONTH=$MONTH DAY=$DAY WEEK=$WEEK"
 
-### Prepare date and period information
-PERIOD=$("$DIR_BIN"/get_period_now $YEAR $MONTH $DAY $WEEK)
-NOW="${YEAR}${MONTH}"
-CNT_KEEP=$("$DIR_BIN"/cnt_keep_by_period $PERIOD)
-echo "YEAR=${YEAR} MONTH=${MONTH} DAY=${DAY} WEEK=${WEEK} PERIOD=${PERIOD} NOW=${NOW} KEEP=$CNT_KEEP"
-
-"$DIR_BIN"/prepare_remote $PERIOD $CNT_KEEP
+echo "$DIR_BIN/prepare_remote"
+"$DIR_BIN"/prepare_remote || exit_if_error $?
 
 #do all backup script
 SCRIPTS=' backup_db backup_data '
 #SCRIPTS=' backup_db  '
 #SCRIPTS=' backup_data '
-for SCRIPT in $SCRIPTS;
+for SCRIPT in $SCRIPTS ;
 do 
-  echo "Executing: $SCRIPT"
-  echo "$DIR_BIN"/$SCRIPT $PERIOD $YEAR $MONTH $DAY $WEEK "$DIR_ROOT"
-       "$DIR_BIN"/$SCRIPT $PERIOD $YEAR $MONTH $DAY $WEEK "$DIR_ROOT"
+  echo "Executing: $DIR_BIN/$SCRIPT $YEAR $MONTH $DAY $WEEK"
+ "$DIR_BIN"/"$SCRIPT" $YEAR $MONTH $DAY $WEEK || exit_if_error $?
 done
 
 exit 0
diff --git a/start_backup b/start_backup
--- a/start_backup
+++ b/start_backup
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+echo
+echo "--- Start $0 $*"
+
 set -o nounset
 set -e 
 
@@ -8,39 +11,38 @@ ERROR_FILE='backup_error.log'
 MSG_ERROR='Error! Check backup'
 
 echo
-echo '------------------------------------------------'
-echo "$0"
-echo 'Start:' $(date +"%D %T")
-echo '------------------------------------------------'
+echo '---'
+echo "$0 $*"
+echo 'Start at '$(date +"%D %T")
+echo '---'
 echo
 
-### Setup your defauly root of directory
-DEF_ROOT='/root/server-back-scripts'
+### Setup your default directories.
+DIR_ROOT=$(dirname "$0")
+DIR_ROOT=$("$DIR_ROOT"/bin/get_root_dir "$0") || exit_if_error $? "Check getting root dirs for $0"
+DIR_BIN="$DIR_ROOT"/bin
+DIR_CFG="$DIR_ROOT"/cfg
+DIR_ARC="$DIR_ROOT"/arc
+DIR_LOG="$DIR_ROOT"/log
 
-START_DIR=$PWD
-
-if [[ -d "$DEF_ROOT/bin" && -d "$DEF_ROOT/cfg" ]]; 
+if [ -d "$DIR_BIN" -a -d "$DIR_CFG"  -a -d "$DIR_ARC"  -a -d "$DIR_LOG" ]; 
 then
-
-  cd "$DEF_ROOT"
   
   ### Input parameters ###
   YEAR=${1:-$(date +"%y")}
   MONTH=${2:-$(date +"%m")}
   DAY=${3:-$(date +"%d")}
   WEEK=${4:-$(date +"%w")}
-  DIR_ROOT=${5:-$DEF_ROOT}
-
-  DIR_BIN="${DIR_ROOT}"/bin
-  DIR_CFG="${DIR_ROOT}"/cfg
-  DIR_ARC="${DIR_ROOT}"/arc
-  DIR_LOG="${DIR_ROOT}"/log
 
   rm -f "$DIR_LOG"/"$ERROR_FILE"
+  echo "$DIR_ROOT/full_backup $YEAR $MONTH $DAY $WEEK"
+  "$DIR_ROOT"/full_backup $YEAR $MONTH $DAY $WEEK
 
-  $DIR_ROOT/full_backup $YEAR $MONTH $DAY $WEEK "$DIR_ROOT"
+  if [[ $? != "0" ]] ; then
+    echo "Error when 'full_backup $YEAR $MONTH $DAY $WEEK'. Check log" | mail -s "$ERROR_MESS" "$MAIL_TO"
+  fi
 
-  if [[ -f "${DIR_LOG}/${ERROR_FILE}" ]] ; then
+  if [[ -f "$DIR_LOG/$ERROR_FILE" ]] ; then
     cat "$DIR_LOG"/"$ERROR_FILE" | mail -s "$ERROR_MESS" "$MAIL_TO"
   fi
 
@@ -48,12 +50,11 @@ else
   echo 'It war error when backup. Check start directory.' | mail -s "$ERROR_MESS" "$MAIL_TO"
 fi
 
-cd "$START_DIR"
-
-
 echo
-echo '------------------------------------------------'
+echo '---'
 echo "$0"
-echo 'Finish:' $(date +"%D %T")
-echo '------------------------------------------------'
+echo 'Finish at '$(date +"%D %T")
+echo '---'
 echo
+
+exit 0
